import { Link as LinkType, Preferences, User } from "@prisma/client";
import {
  Bio,
  SocialLink,
  UserImage,
  UserIndicator,
  UserLink,
} from "../Components";
import EditIndicators from "../admin/EditIndicators";
import EditSocials from "../admin/EditSocials";
import {
  AiOutlineInstagram,
  AiOutlineLinkedin,
  AiOutlineTwitter,
} from "react-icons/ai";
import AddLink from "../admin/AddLink";
import Logo from "@/components/base/Logo";
import Link from "next/link";
import Settings from "../admin/Settings";
import SignOut from "@/components/auth/SignOut";

const Default = ({ user, admin }: { user: User; admin?: boolean }) => {
  // TODO: TS ERROR
  return (
    <div className="max-w-[600px] m-auto py-12 flex flex-col items-center justify-center gap-7">
      <section
        id="indicators"
        className="mx-5 flex flex-col justify-center items-center gap-4"
      >
        <UserImage
          image={user.image}
          username={user.username}
          theme={"DEFAULT"}
        />
        <UserIndicator
          username={
            user.preferences.showNameAs === "USERNAME"
              ? user.username
              : undefined
          }
          name={user.preferences.showNameAs === "NAME" ? user.name : undefined}
        />
        <Bio bio={user.bio} />
        {admin ? (
          <div className="flex flex-wrap justify-center gap-3">
            <EditIndicators user={user} theme={"DEFAULT"} />
            <Settings user={user} theme={"DEFAULT"} />
            <SignOut theme={"DEFAULT"} />
          </div>
        ) : (
          <></>
        )}
      </section>
      <section id="socials" className="mx-5 flex flex-wrap justify-center gap-3 items-center">
        {user.socials.instagram ? (
          <SocialLink
            title="Instagram"
            icon={<AiOutlineInstagram />}
            url={"https://instagram.com"}
            href={user.socials?.instagram}
            theme={"DEFAULT"}
          />
        ) : (
          <></>
        )}
        {user.socials.linkedin ? (
          <SocialLink
            title="Linkedin"
            icon={<AiOutlineLinkedin />}
            url={"https://linkedin.com/in"}
            href={user.socials?.linkedin}
            theme={"DEFAULT"}
          />
        ) : (
          <></>
        )}
        {user.socials.twitter ? (
          <SocialLink
            title="Instagram"
            icon={<AiOutlineTwitter />}
            url={"https://twitter.com"}
            href={user.socials?.twitter}
            theme={"DEFAULT"}
          />
        ) : (
          <></>
        )}
        {!user.socials.instagram &&
        !user.socials.linkedin &&
        !user.socials.twitter ? (
          <div className="text-xl">👾 {user.name} has no social links</div>
        ) : (
          <></>
        )}
        {admin ? <EditSocials user={user} theme={"DEFAULT"} /> : <></>}
      </section>
      <section
        id="links"
        className="mx-5 flex w-full flex-col items-center justify-center gap-8"
      >
        {user.links.length !== 0 ? (
          <>
            {user.links.map((link: LinkType, i: number) => {
              return (
                <UserLink
                  key={i}
                  id={link.id}
                  title={link.title}
                  href={link.href}
                  icon={link.icon ? link.icon : undefined}
                  target={link.target}
                  admin={admin ? admin : false}
                  theme={"DEFAULT"}
                />
              );
            })}
          </>
        ) : (
          <div className="text-lg">☹️ {user.name} has no links</div>
        )}
        {admin ? <AddLink user={user} theme={"DEFAULT"} /> : <></>}
      </section>
      <section id="linkfold" className="mx-5 flex items-center gap-2">
        <div>Generated by</div>{" "}
        <Link href={admin ? "" : "/"} className="p-2 border border-black">
          <Logo />
        </Link>
      </section>
    </div>
  );
};

export default Default;
